/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as MatchmakerRouteImport } from './routes/matchmaker'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as HelpRouteImport } from './routes/help'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArtistsRouteImport } from './routes/artists'
import { Route as AdvisorRouteImport } from './routes/advisor'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookIdRouteImport } from './routes/book.$id'
import { Route as ArtistsIdRouteImport } from './routes/artists.$id'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchmakerRoute = MatchmakerRouteImport.update({
  id: '/matchmaker',
  path: '/matchmaker',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsRoute = ArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorRoute = AdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIdRoute = BookIdRouteImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsIdRoute = ArtistsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ArtistsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/advisor': typeof AdvisorRoute
  '/artists': typeof ArtistsRouteWithChildren
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/cookies': typeof CookiesRoute
  '/guide': typeof GuideRoute
  '/help': typeof HelpRoute
  '/maintenance': typeof MaintenanceRoute
  '/matchmaker': typeof MatchmakerRoute
  '/packages': typeof PackagesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/timeline': typeof TimelineRoute
  '/wishlist': typeof WishlistRoute
  '/artists/$id': typeof ArtistsIdRoute
  '/book/$id': typeof BookIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/advisor': typeof AdvisorRoute
  '/artists': typeof ArtistsRouteWithChildren
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/cookies': typeof CookiesRoute
  '/guide': typeof GuideRoute
  '/help': typeof HelpRoute
  '/maintenance': typeof MaintenanceRoute
  '/matchmaker': typeof MatchmakerRoute
  '/packages': typeof PackagesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/timeline': typeof TimelineRoute
  '/wishlist': typeof WishlistRoute
  '/artists/$id': typeof ArtistsIdRoute
  '/book/$id': typeof BookIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/advisor': typeof AdvisorRoute
  '/artists': typeof ArtistsRouteWithChildren
  '/auth': typeof AuthRoute
  '/bookings': typeof BookingsRoute
  '/cookies': typeof CookiesRoute
  '/guide': typeof GuideRoute
  '/help': typeof HelpRoute
  '/maintenance': typeof MaintenanceRoute
  '/matchmaker': typeof MatchmakerRoute
  '/packages': typeof PackagesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/timeline': typeof TimelineRoute
  '/wishlist': typeof WishlistRoute
  '/artists/$id': typeof ArtistsIdRoute
  '/book/$id': typeof BookIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/advisor'
    | '/artists'
    | '/auth'
    | '/bookings'
    | '/cookies'
    | '/guide'
    | '/help'
    | '/maintenance'
    | '/matchmaker'
    | '/packages'
    | '/privacy'
    | '/profile'
    | '/refund'
    | '/reset-password'
    | '/settings'
    | '/sitemap.xml'
    | '/terms'
    | '/timeline'
    | '/wishlist'
    | '/artists/$id'
    | '/book/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/advisor'
    | '/artists'
    | '/auth'
    | '/bookings'
    | '/cookies'
    | '/guide'
    | '/help'
    | '/maintenance'
    | '/matchmaker'
    | '/packages'
    | '/privacy'
    | '/profile'
    | '/refund'
    | '/reset-password'
    | '/settings'
    | '/sitemap.xml'
    | '/terms'
    | '/timeline'
    | '/wishlist'
    | '/artists/$id'
    | '/book/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/advisor'
    | '/artists'
    | '/auth'
    | '/bookings'
    | '/cookies'
    | '/guide'
    | '/help'
    | '/maintenance'
    | '/matchmaker'
    | '/packages'
    | '/privacy'
    | '/profile'
    | '/refund'
    | '/reset-password'
    | '/settings'
    | '/sitemap.xml'
    | '/terms'
    | '/timeline'
    | '/wishlist'
    | '/artists/$id'
    | '/book/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AdvisorRoute: typeof AdvisorRoute
  ArtistsRoute: typeof ArtistsRouteWithChildren
  AuthRoute: typeof AuthRoute
  BookingsRoute: typeof BookingsRoute
  CookiesRoute: typeof CookiesRoute
  GuideRoute: typeof GuideRoute
  HelpRoute: typeof HelpRoute
  MaintenanceRoute: typeof MaintenanceRoute
  MatchmakerRoute: typeof MatchmakerRoute
  PackagesRoute: typeof PackagesRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  RefundRoute: typeof RefundRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TimelineRoute: typeof TimelineRoute
  WishlistRoute: typeof WishlistRoute
  BookIdRoute: typeof BookIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matchmaker': {
      id: '/matchmaker'
      path: '/matchmaker'
      fullPath: '/matchmaker'
      preLoaderRoute: typeof MatchmakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists': {
      id: '/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor': {
      id: '/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$id': {
      id: '/book/$id'
      path: '/book/$id'
      fullPath: '/book/$id'
      preLoaderRoute: typeof BookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/$id': {
      id: '/artists/$id'
      path: '/$id'
      fullPath: '/artists/$id'
      preLoaderRoute: typeof ArtistsIdRouteImport
      parentRoute: typeof ArtistsRoute
    }
  }
}

interface ArtistsRouteChildren {
  ArtistsIdRoute: typeof ArtistsIdRoute
}

const ArtistsRouteChildren: ArtistsRouteChildren = {
  ArtistsIdRoute: ArtistsIdRoute,
}

const ArtistsRouteWithChildren =
  ArtistsRoute._addFileChildren(ArtistsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AdvisorRoute: AdvisorRoute,
  ArtistsRoute: ArtistsRouteWithChildren,
  AuthRoute: AuthRoute,
  BookingsRoute: BookingsRoute,
  CookiesRoute: CookiesRoute,
  GuideRoute: GuideRoute,
  HelpRoute: HelpRoute,
  MaintenanceRoute: MaintenanceRoute,
  MatchmakerRoute: MatchmakerRoute,
  PackagesRoute: PackagesRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  RefundRoute: RefundRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TimelineRoute: TimelineRoute,
  WishlistRoute: WishlistRoute,
  BookIdRoute: BookIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
